version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - "7000:7000"
  users:
    build: ./users-api
    ports: 
      - "8080:8080"
    environment:
      AUTH_SERVICE_SERVICE_HOST: "auth:7000"
  tasks:
    build: ./tasks-api
    ports: 
      - "8000:8000"
    environment:
      TASKS_FOLDER: tasks
      AUTH_SERVICE_SERVICE_HOST: "auth:7000"
    
