apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: "TCP"
      # external port
      port: 80
      # container port
      targetPort: 8080
  type: LoadBalancer