---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # only reachable within cluster
  type: ClusterIP 
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000 