---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: wstrellis/kub-users-app:latest 
          env:
            - name: AUTH_ADDRESS
            # ip address of auth service shown from "kubectl get services"
              value: "10.103.21.224:7000"